use std::error::Error;

mod day01;

fn main() -> Result<(), Box<dyn Error>> {
    day01::part2()
}
